/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DebitCardsRouteImport } from './routes/debit-cards'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DebitCardsRoute = DebitCardsRouteImport.update({
  id: '/debit-cards',
  path: '/debit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/debit-cards': typeof DebitCardsRoute
  '/features': typeof FeaturesRoute
  '/personal': typeof PersonalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/debit-cards': typeof DebitCardsRoute
  '/features': typeof FeaturesRoute
  '/personal': typeof PersonalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/debit-cards': typeof DebitCardsRoute
  '/features': typeof FeaturesRoute
  '/personal': typeof PersonalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/debit-cards'
    | '/features'
    | '/personal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/business' | '/debit-cards' | '/features' | '/personal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/debit-cards'
    | '/features'
    | '/personal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  DebitCardsRoute: typeof DebitCardsRoute
  FeaturesRoute: typeof FeaturesRoute
  PersonalRoute: typeof PersonalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debit-cards': {
      id: '/debit-cards'
      path: '/debit-cards'
      fullPath: '/debit-cards'
      preLoaderRoute: typeof DebitCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  DebitCardsRoute: DebitCardsRoute,
  FeaturesRoute: FeaturesRoute,
  PersonalRoute: PersonalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
